#cmakedefine BASEDIR "${CMAKE_INSTALL_PREFIX}/${BASEDIR}"
#cmakedefine BITMAPDIR "${CMAKE_INSTALL_PREFIX}/${BITMAPDIR}"
#cmakedefine BINARYDIR "${CMAKE_INSTALL_PREFIX}/${BINARYDIR}"
#cmakedefine DOCDIR "${CMAKE_INSTALL_PREFIX}/${DOCDIR}"
#cmakedefine LANGUAGEDIR "${CMAKE_INSTALL_PREFIX}/${LANGUAGEDIR}"
#cmakedefine LIBRARYDIR "${CMAKE_INSTALL_PREFIX}/${LIBRARYDIR}"

#define PACKAGE_VERSION "0.1.0"
#define PACKAGE_STRING "qucs 0.1.0"
