.TH Caneda "1" "October 2015" "Debian GNU/Linux" "User Commands"
.SH NAME
Caneda \- Open source EDA software.
.SH SYNOPSIS
.B caneda
[\fIOPTION\fR] ...
.SH DESCRIPTION

\fBCaneda\fR is an open source EDA software focused on easy of use and
portability. Caneda's goal is the complete design proccess from schematic
capture, through simulation and into circuit layout and PCB.

While in the short term schematic capture and simulation is the primary goal,
in the long term future, PCB and layout edition will be covered. The software
aims to support all kinds of circuit simulation types, e.g. DC, AC, S-parameter
and harmonic balance analysis.

.SH AVAILABILITY
The latest version of Caneda can always be obtained from
\fBhttps://github.com/Caneda/Caneda\fR
.SH "REPORTING BUGS"
Please report bugs to
\fBhttps://github.com/Caneda/Caneda/issues\fR
.SH COPYRIGHT
Copyright \(co 2009-2016 Pablo Daniel Pareja Obregón <parejaobregon@gmail.com>
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
Written by Pablo Daniel Pareja Obregón <parejaobregon@gmail.com>